### ISSUE TITLE
Error when start bot

### ISSUE THREAD

**Issue by osnipezzini** [ArrowsX/musicbot#3]
root@root:~/musicbot# python3 bot.py
2016-08-26 06:43:52,045 - telegram.ext.updater - ERROR - unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 104, in _thread_wrapper
    target(_args, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 215, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='')
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 319, in _bootstrap
    self.bot.setWebhook(webhook_url=webhook_url, certificate=cert)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 121, in decorator
    result = func(self, _args, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 1263, in setWebhook
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 235, in post
    *_urlopen_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 178, in _request_wrapper
    raise Unauthorized()
telegram.error.Unauthorized: Unauthorized
Exception in thread updater:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(_self._args, *_self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 104, in _thread_wrapper
    target(_args, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 215, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='')
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 319, in _bootstrap
    self.bot.setWebhook(webhook_url=webhook_url, certificate=cert)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 121, in decorator
    result = func(self, *args, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 1263, in setWebhook
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 235, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telegram/utils/request.py", line 178, in _request_wrapper
    raise Unauthorized()
telegram.error.Unauthorized: Unauthorized

2016-08-26 06:43:52,843 - telegram.ext.dispatcher - CRITICAL - stopping due to exception in another thread

**Comment by glumia** [comment]
It's a problem with the bot token, try to get one for yourself talking with the bothfather (https://core.telegram.org/bots#6-botfather) and edit the credentials.py file.
